[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[target.'cfg(target_os = "none")']
runner = "cargo run --package boot --"

[alias]
ktest = "test --target x86_64-target.json -- --no-display"
kbuild = "build --target x86_64-target.json"
kimage = "run --target x86_64-target.json -- --no-run"
krun = "run --target x86_64-target.json"
